event/urls.py
from django.urls import path, include
from event import views
from comment.views import comment_detail, comment_create_ajax

app_name = 'event'

urlpatterns = [
    path('register/', views.register_event, name="event_register"),
    path('creator_event/<int:pk>/',views.creator_detail, name='creator_detail'),
    path('creator_event/<int:pk>/comment/', comment_detail, name='comment_detail'),
    path('creator_event/<int:pk>/comment/create/', comment_create_ajax, name='comment_create_ajax'),
    path('search_result/', views.search_result, name='search_result'),
    path('search_result_click/<str:tag>', views.search_result_click, name='search_result_click'),

    path('today_event/', views.today_event, name="today_event"),

    path('creator_event/<int:pk>/delete', views.event_delete, name="event_delete"),
]

event/models.py
from django.db import models
from login.models import Creator
from location.models import Event_Location
from datetime import datetime
from django.utils import timezone
# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=100)

class Event(models.Model):
    location = models.ForeignKey(Event_Location, on_delete=models.CASCADE,default=None)
    creator = models.ForeignKey(Creator, on_delete=models.CASCADE,default=None, related_name='events')
    event_name = models.CharField(max_length=200, blank=False, verbose_name="이벤트 이름")
    desc = models.TextField(blank=True, verbose_name="이벤트 소개")

    start_date_time = models.DateTimeField(auto_now=False, blank=False, default=timezone.now, verbose_name="이벤트 시작 날짜/시간")
    end_date_time = models.DateTimeField(auto_now=False, blank=False, default=timezone.now, verbose_name="이벤트 종료 날짜/시간")

    tags = models.ManyToManyField(Tag, verbose_name="태그")

    GENRE_LIST = (
        ('Busking', '버스킹'),
        ('Flea', '플리마켓'),
        ('Exhibit', '전시'),
    )
    genre = models.CharField(max_length=100, choices=GENRE_LIST, verbose_name="이벤트 장르")

    def __str__(self):
        return self.event_name


class EventImage(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, default=None)
    image = models.ImageField(upload_to='event_images/%Y/%m/%d', verbose_name="이벤트 이미지")

event/templates/event/creator_event_detail.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style %}
    <link rel="stylesheet" href="{% static 'event/css/creator_detail.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@1,400;1,500&family=Jua&family=Lobster&family=Yeon+Sung&display=swap" rel="stylesheet">
{% endblock %}

{% block main %}
<!--header-->
{% if event.genre == 'Busking' %}
    <div class='header' style="background: url('{% static 'event/img/busk.jpg' %}') no-repeat;
    background-size: 100% auto; height:350px;">
{% elif event.genre == 'Flee' %}
    <div class='header' style="background: url('{% static 'event/img/flea.png' %}') no-repeat;
    background-size: 100% auto; height:350px">
{% else %}
    <div class='header' style="background: url('{% static 'event/img/exhibit.png' %}') no-repeat;
    background-size: cover; height:300px">
{% endif %}
    <div class='flex-item'>
    {% if event.genre == 'Busking' %}
        <p id='genre'>Busking</p>
    {% elif event.genre == 'Flee' %}
        <p id='genre'>Flea Market</p>
    {% else %}
        <p id='genre'>Exhibition</p>
    {% endif %}
        <div class="line"></div>
        <br/>
        <h2 id='creator_name' style="font-weight: bold;">{{ event.creator.creator_name }}<span style="font-weight: lighter;">'s Page</span></h2>
        <span>
            {% if user in event.creator.like_users.all %}
                <a href="{% url 'login:like_creator' %}" class="like" name="{{ event.id }}">
                    <i class="fas fa-heart fa-2x" ></i>
                </a>
            {% else %}
                <a href="{% url 'login:like_creator' %}" class="like" name="{{ event.id }}">
                    <i class="far fa-heart fa-2x" ></i>
                </a>
            {% endif %}
        </span>
    </div>
</div>

<!--content-->
<div class="container_wrapper" style="margin-top: 30px;">
    <div class="container first_content">
        <div class="row">
            <div class="col-lg-6 col-md-12 content_1">
                <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        {% for event_image in images %}
                            {% if forloop.first %}
                            <div class="carousel-item active" data-interval="4000">
                            <div class="imgwrapper">
                            <img src="{{ event_image.image.url }}" alt="background" style=""></div>
                            </div>
                            {% else %}
                            <div class="carousel-item" data-interval="4000">
                            <img src="{{ event_image.image.url }}" alt="background" style="">
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
            <div class="col-lg-6 col-md-12 content_2">
                <div class="grid-item">
                    <h2 id="title" style="margin: 0;">Event Information</h2>
                    <hr/>
                    <br>
                    <p id="event_name">{{event.event_name}}</p>
                    <p id="event_time"><b>일시</b>: {{event.start_date_time}} ~ {{event.end_date_time}}</p>
                    <p id="event_location"><b>장소</b>: {{event.location.city}} {{event.location.gu}} {{event.location.rest_address}}</p>
                    <p id="event_desc"><b>설명</b>: {{event.desc|linebreaksbr}}</p>
                    <br>
                    <p id='tag_name'>
                    {% for tag in tags %}
                        <a href="{% url 'event:search_result_click' tag.name %}"><button id="tag-box">{{tag.name}}</button></a>
                    {% endfor %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container_wrapper">
    <div class="container history">
        <div class="line"></div>
        <h2 id="title">Event History</h2>
        <p id='title_desc'> <b>'{{ event.creator.creator_name }}'</b> 님의 이벤트 진행 기록들을 확인할 수 있어요!</p>
        {% for creator_event in events %}
        <div class="row history_event">
            <div class="col-lg-7 col-md-12 history_col">
                <div class="infowrapper">
                    <p id="event_name"><a href="{% url 'event:creator_detail' creator_event.pk %}">{{creator_event.event_name}}</a></p>
                    <p id="event_time"><b>일시</b>: {{creator_event.start_date_time}} ~ {{creator_event.end_date_time}}</p>
                    <p id="event_location"><b>장소</b>: {{creator_event.location.city}} {{creator_event.location.gu}} {{creator_event.location.rest_address}}</p>
                    <p id="event_desc"><b>설명</b>: {{creator_event.desc}}</p>
                    <p id='tag_name'>
                        {% for tag in creator_event.tags.all %}
                        <a href="{% url 'event:search_result_click' tag.name %}"><button id="tag-box">{{tag.name}}</button></a>
                        {% endfor %}
                    </p>
                </div>
            </div>
            <div class="col-lg-5 d-none d-lg-block history_col">
                <!--{{creator_event.eventimage_set.all}}-->
                <img src="{{creator_event.eventimage_set.all.first.image.url}}" alt="" class='history_imgs'/>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<div class="container_wrapper">
    <div class="container comment_list">
        <div class="line"></div>
        <h2 id='title'>Visitor Book</h2>
        <p id='title_desc'> <b>'{{ event.creator.creator_name }}'</b> 님의 방명록을 확인할 수 있어요!</p>
        
        {% for comment in comment_3 %}
            {% if forloop.first %}
            <div class="row">
                <div class="col my-auto"><img src="{% static 'event/img/user1.png' %} " alt="" class='comment_user'><br>{{comment.member.nickname}}</div>
                <div class="col grid2 speech-bubble1 my-auto">
                    <div class="grid-item2 left">
                        <b>{{comment.comment_text}}</b><br>
                        <small>{{comment.created_at}}</small>
                    </div>
                </div>
                <br>
            </div>
            {% elif forloop.last %}
            <div class="row">
                <div class="col my-auto"><img src="{% static 'event/img/user3.png' %} " alt="" class='comment_user'><br>{{comment.member.nickname}}</div>
                <div class="col grid2 speech-bubble1 my-auto">
                    <div class="grid-item2 left">
                        <b>{{comment.comment_text}}</b><br>
                        <small>{{comment.created_at}}</small>
                    </div>
                </div>
                <br>
            </div>
            {% else %}
            <div class="row">
            <div class="col grid2 speech-bubble2 my-auto">
                <div class="grid-item2 right">
                    <b>{{comment.comment_text}}</b><br>
                    <small>{{comment.created_at}}</small>
                </div>
            </div>
                <div class="col my-auto"><img src="{% static 'event/img/user2.png' %} " alt="" class='comment_user'><br>{{comment.member.nickname}}</div>
                 <br>
            </div>
            {% endif %}
        {% endfor %}
        <div class="row">
            {% if comment_num != 0 %}
            <div class="col">
                <a href="{% url 'event:comment_detail' creator.pk %}" class="btn btn-outline-success my-2 my-sm-0">더보기</a>
            </div>
            {% else %}
            <div class="col">
                <p>후기가 아직 없어요!</p>
                <a href="{% url 'event:comment_detail' creator.pk %}" class="btn btn-outline-success my-2 my-sm-0">후기 작성하러가기</a>
            </div>
            {% endif %}

        </div>
    </div>
</div>
{% endblock %}

{% block injiscript %}
    <script>
    $('.carousel').carousel({interval: 2000,})
    </script>
{% endblock %}
{% block kiyunscript %}
    <script src="https://kit.fontawesome.com/7d6a50a6b2.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{% static 'login/js/like.js' %}"></script>
{% endblock %}

event/templates/event/event_register.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style %}
    <link rel="stylesheet" href="{% static 'event/css/register.css' %}">
{% endblock %}

{% block main %}
    {% if user.is_authenticated %}

    <div class="registering">
        <div class="wrapping">
        <h1 style="color: #dd445b;">이벤트 등록하기</h1>
        <h4><b>{{ creator.creator_name }}</b> 님의 개성있는 이벤트를 등록해주세요</h4>
        <hr/>
        <br/>
        <div class="wrap row">
            <!-- 사용자의 선호 지역을 받기 위한 구역(보이지는 않음) -->
            <div class="template_variable_section">
                <div class="template_variable_city">{{prefer_city}}</div>
                <div class="template_variable_gu">{{prefer_gu}}</div>
            </div>
            <div class="choose_section row col-md-3 col-sm-12 col-xs-12">
                <div class="choose_city row col-md-12 col-sm-12 col-xs-12">
                    <label for="city" class="col-md-12 col-sm-12 col-xs-12">도시 선택</label>
                    <select
                        name="city"
                        id="city"
                        onchange="addressKindChange(this)"
                        class="selected_city col-md-12 col-sm-12 col-xs-12"
                    >
                        <option class="col-md-12 col-sm-12 col-xs-12">도시를 선택해주세요</option>
                        <option value="서울특별시">서울특별시</option>
                    </select>
                </div>
                <div class="choose_gu col-md-12 col-sm-12 col-xs-12">
                    <label for="gu" class="col-md-12 col-sm-12 col-xs-12">구 선택</label>
                    <select name="gu" id="gu" class="selected_gu col-md-12 col-sm-12 col-xs-12">
                        <option class="col-md-12 col-sm-12 col-xs-12">구를 선택해주세요</option>
                    </select>
                </div>
                <div class="search_btn_section col-md-12 col-sm-12 col-xs-12">
                    <button
                    type="button"
                    class="btn btn-primary search_btn"
                    onclick="map_reset(this)"
                    >
                    검색
                    </button>
                </div>
            </div>
            <div class="map_wrap col-md-9 col-sm-12 col-xs-12">
                <div id="map"></div>
                <div class="hAddr">
                    <span id="centerAddr"></span>
                </div>
            </div>
        </div>
        <form id="event_form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                {{ form }}
                {{ formset.management_form }}
                <br/><br/>
                <label for="sdt">이벤트 시작 날짜/시간 : </label>
                <input id="sdt" type="datetime-local" name="start_date_time"/>
            <br/>
                <label for="edt">이벤트 종료 날짜/시간 : </label>
                <input id="edt" type="datetime-local" name="end_date_time"/>
<br/><br/>
                {% for imageform in formset %}
                    {{ imageform|linebreaks }}
                {% endfor %}
<br/>
            <label for="tag_input">태그(많이 할수록 검색에 잘 걸려요!)</label>
            <input id="tag_input" name="tag" type="text" size=100 placeholder="ex) 플리마켓, 목걸이, 감성, 가성비">
            <br>
            <div class="location_form_section">
                {{ location }}
            </div>
            <div class="input_div">
                <input id="enroll_btn" type="submit" value="이벤트 등록">
            </div>
            <br/>
            <br/>
            <br/>

        </form>
        </div>
    </div>

    <div class="register_info">
    <h4>이벤트 등록 방법</h4> <hr/><br/>
            <div>
                <div class="event_helptext">
                    <img src="/static/img/black_check.png" alt="">
                    <p>'이벤트 장소'는 특정 건물뿐만 아니라 길거리 어디든 설정할 수 있어요. <br/>먼저 원하는 도시와 구를 선택한 후, 우측의 지도를 통해 원하는 위치를 클릭하세요.</p>
                </div>
                <div class="event_helptext">
                    <img src="/static/img/black_check.png" alt="">
                    <p>'이벤트 종류'는 버스킹, 플리마켓, 전시 총 세가지 카테고리 중 하나를 선택하실 수 있습니다. <br/>이벤트에 대해 추가로 설명이 필요한 부분은 '이벤트 소개'에서 자유롭게 작성해주세요.</p>
                </div>
                <div class="event_helptext">
                    <img src="/static/img/black_check.png" alt="">
                    <p>'이벤트 사진'은 0개에서 최대 3개까지 업로드하실 수 있습니다. <br/>관람객들에게 이벤트의 분위기를 한눈에 보여줄 수 있는 중요한 요소이니, 이벤트의 성격에 맞는 사진을 신중히 골라주세요!</p>
                </div>
                <div class="event_helptext">
                    <img src="/static/img/black_check.png" alt="">
                    <p>'태그'에는 이벤트를 잘 나타낼 수 있는 키워드를 작성하시면 됩니다. <br/>검색은 '태그'를 기준으로 분류되니, '크리에이터명' '이벤트 이름' '이벤트 종류'를 포함하여 최대한 다양하게 작성해주세요.</p>
                </div>
            </div>
    </div>
    {% else %}
        <script type="text/javascript">
            alert('로그인이 필요합니다')
            window.location.href = '{% url "login:login" %}';
        </script>
    {% endif %}
{% endblock %}


{% block jinheescript %}
<script
  type="text/javascript"
  src="//dapi.kakao.com/v2/maps/sdk.js?appkey=4be94fffa6f06598b351be42b3a70113&libraries=services"
></script>
<script src={% static 'event/js/register.js' %}></script>
{% endblock %}

event/templates/event/search_result.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style %}
    <link rel="stylesheet" href="{% static 'event/css/search_result.css' %}">
{% endblock %}

{% block main %}
    <div class="container">
    <div class="top-desc">
<!--        <img src="/static/img/search.png" alt="search icon">-->
        <p>"<b>{{ data }}</b>"를 포함한 태그를 가진 이벤트 검색결과</p>
    </div>
    {% if results is None %}
        <div class="top-desc">
            검색결과가 없습니다<br><br>
            <img id="not-found-img" src="{% static "event/img/emojis.png" %}">
        </div>
    {% elif data == "" %}
        <div class="top-desc">
            검색어가 없습니다. 검색어를 입력해주세요!<br><br>
            <img id="not-found-img" src="{% static "event/img/emojis.png" %}" >
        </div>
    {% else %}

        <div class="events-container">
        {% for event in results %}
            <a href="{% url "event:creator_detail" event.pk %}" class="goto_detail">
                <div class="row s_event-container ">
                    <div class="col-12 col-md-auto" id="left_section">
{#                    <div id="left_section">#}
                        <div id="event_name">
                            {{ event.event_name }}
                        </div>
                        <div id="creator_name_like">
                            <div id="name">
                                크리에이터 : <b>{{ event.creator.creator_name }}</b>
                            </div>
                            <div id="like">
                                {% if user in event.creator.like_users.all %}
                                    <a href="{% url 'login:like_creator' %}" class="like" name="{{ event.id }}">
                                        <i class="fas fa-heart" ></i>
                                    </a>
                                {% else %}
                                    <a href="{% url 'login:like_creator' %}" class="like" name="{{ event.id }}">
                                        <i class="far fa-heart" ></i>
                                    </a>
                                {% endif %}
{#                                <p id="count-{{ event.creator.id }}">{{ event.creator.like_count }}개</p>#}
                            </div>

                        </div>
                        <div id="loc">
                                {{ event.location.city }}시 {{ event.location.gu }}
                        </div>
                        <hr/>
                        <div id="event_desc">
                            {{ event.desc|linebreaksbr}}<br>
                        </div>
                        <hr/>
                        <div id="event_time">
                            <b>{{ event.end_date_time.month }}월 {{ event.end_date_time.day }}일 {{ event.end_date_time.time }}</b>에 이벤트가 끝나요!
                        </div>
                        <br/>
                        {% for tag in event.tags.all %}
                            <a href="{% url "event:search_result_click" tag.name %}">
                                <div id="tag-box">{{ tag.name }}</div>
                            </a>
                        {% endfor %}
                    </div>

                    <div class="col-12 col-md-auto" id="right_section">
{#                    <div id="right_section">#}
                        <img src="{{ event.eventimage_set.first.image.url }}" alt="이미지1">
                    </div>
                </div>
            </a>
        {% endfor %}
        </div>

    {% endif %}
    </div>

{% endblock %}

{% block kiyunscript %}
    <script src="https://kit.fontawesome.com/7d6a50a6b2.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="{% static 'login/js/like.js' %}"></script>
{% endblock %}

event/templates/event/today_event.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style %}
<link rel="stylesheet" href="{% static 'event/css/today_event.css' %}">
{% endblock %}

{% block main %}
<div class="entire_wrapper">
    <div class="container_wrapper">
        <h1 style="color: #dd445b;">오늘의 이벤트</h1>
        <h5><b>{{user.nickname}}</b> 님의 선호지역인
            <b>{{user.city}} {{user.gu}}</b> 기반으로 검색된 결과입니다.
            <!-- <a href='{% url "login:main" %}'><button>다른지역 검색하러 가기</button></a> -->
        </h5>
        <hr>

    </div>
    <div class="buttons">
        <div>
            <a href="#container1">
                <button type="button" class="filter_btn">시작전</button>
            </a>
            <a href="#container2">
                <button type="button" class="filter_btn">진행중</button>
            </a>
            <a href="#container3">
                <button type="button" class="filter_btn">마감</button>
            </a>
        </div>

    </div>

    <div class='container_wrapper2'>
        <div class='col-lg-12 col-md-12 main'>
            <div class="container1" id="container1">
                <div class="row event_header" id="eventheader1">
                    <h3>시작 전 이벤트</h3>
                </div>
                <br/>
                <div id="tabContent1" class="row not_yet_event">
                    {% for not_yet_event in not_yet_events.all %}
                    {% if not_yet_event.location.city == user.city and not_yet_event.location.gu == user.gu %}
                    <div class='col-lg-4 col-md-12 not_yet_event_section'>
                        <p>이벤트 이름 : {{ not_yet_event.event_name }}</p><br>
                        
                        <div class='hovereffect'>
                            <img src="{{ not_yet_event.eventimage_set.all.first.image.url }}" alt=""
                                 class='history_imgs1'>
                            <div class="overlay">
                                <h2>{{ not_yet_event.get_genre_display }}</h2>
                                <p>
                                    <b>두근두근! 곧 시작해요🤩</b><br>
                                    {{ not_yet_event.start_date_time.time }}
                                    {{ not_yet_event.end_date_time.time }}<br>
                                    <a href="{% url 'event:creator_detail' not_yet_event.creator.pk %}">{{ not_yet_event.genre }} LINK</a>
                                </p>
                            </div>
                        </div>
                    </div>

                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            <br/><br/>
            <div class="container2" id="container2">
                <div class="row event_header" id="eventheader2">
                    <h3>진행중인 이벤트</h3>
                </div>
                <br/>
                <div id="tabContent2" class="row ing_event">
                    {% for ing_event in ing_events.all %}
                    
                    {% if ing_event.location.city == user.city and ing_event.location.gu == user.gu %}
                    <div class='col-lg-4 col-md-12 ing_event_section'>
                        <p>이벤트 이름 : {{ ing_event.event_name }}</p><br>
                        <div class='hovereffect'>
                            <img src="{{ ing_event.eventimage_set.all.first.image.url }}" alt="" class='history_imgs2'>
                            <div class="overlay">
                                <h2>{{ ing_event.get_genre_display }}</h2>
                                <p>
                                    <b>아직 진행 중이에요😎</b><br>
                                    {{ ing_event.start_date_time.time}} ~
                                    {{ ing_event.end_date_time.time }}<br>
                                    <a href="{% url 'event:creator_detail' ing_event.creator.pk %}">{{ ing_event.genre }} LINK</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>

            <br/><br/>
            <div class="container3" id="container3">
                <div class="row event_header" id="eventheader3">
                    <h3>종료한 이벤트</h3>
                </div>
                <br/>
                <div id="tabContent3" class='row end_event'>
                    {% for end_event in end_events.all %}
                    {% if end_event.location.city == user.city and end_event.location.gu == user.gu %}
                    <div class='col-lg-4 col-md-12 end_event_section'>
                        <p>이벤트 이름 : {{ end_event.event_name }}</p>
                        <div class='hovereffect'>
                            <img src="{{ end_event.eventimage_set.all.first.image.url }}" alt="" class='history_imgs3'>
                            <div class="overlay">
                                <h2>{{ end_event.get_genre_display }}</h2>
                                <p>
                                    <b>아쉽지만 종료되었어요😢</b><br>
                                    {{ end_event.start_date_time.time}} ~
                                    {{ end_event.end_date_time.time }}<br>
                                   <a href="{% url 'event:creator_detail' end_event.creator.pk %}">크리에이터 LINK</a>
                                </p>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>
</div>


{% endblock %}


{% block hanseokscript %}
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<!--jquery사용하려면 필요한 스크립트 코드  (메서드 사용 가능하게 해줌)-->
<script>
    $(document).ready(function () {
        $('a[href^="#"]').on('click', function (e) {
            e.preventDefault();

            var target = this.hash;
            var $target = $(target);

            $('html, body').stop().animate({
                'scrollTop': $target.offset().top - 100
            }, 500, 'swing', function () {
                // window.location.hash = target;
            });
        });
    });
    // $(".filter_btn").click(function (event) {
    //         event.preventDefault();
    //         $(html, body).animate({scrollTop: $(this.hash).offset().top}, 500);
    //     });
    // });

    // $(".container1").on("click", function (e) {
    //     e.preventDefault();//anchor이벤트의 기본동작을 막는다.
    //     var thisTarget = $(this).attr("href");
    //     $(window).animate({scrollTop: $(thisTarget).offset().top}, 1000);
    // });
    // $(".eventheader2").on("click", function (e) {
    //     e.preventDefault();//anchor이벤트의 기본동작을 막는다.
    //     var thisTarget = $(this).attr("href");
    //     $(window).scrollTop($(thisTarget).offset().top);
    // });
    // $(".eventheader3").on("click", function (e) {
    //     e.preventDefault();//anchor이벤트의 기본동작을 막는다.
    //     var thisTarget = $(this).attr("href");
    //     $(window).scrollTop($(thisTarget).offset().top);
    // });

</script>

{% endblock %}