comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # path('<int:pk>/',views.comment_detail, name='comment_detail'),
    path('update/<int:comment_id>/', views.comment_update, name='comment_update'),
    path('delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
    path('<int:comment_id>/recomment/', views.recomment_detail, name='recomment_detail'),
    path('<int:comment_id>/recomment/create/', views.recomment_create_ajax, name='recomment_create_ajax'),
    path('<int:comment_id/recomment/delete/<int:recomment_id>/', views.recomment_delete, name='recomment_delete'),
    # path('create/', views.comment_create_ajax, name='comment_create_ajax'),
    # path('creator_event/<int:pk>/',views.creator_detail, name='creator_detail'),
    # path('creator_event/<int:pk>/detail', comment_detail, name='comment_detail'),
]

comment/models.py
from django.db import models
from login.models import Member, Creator


class Comment(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    creator = models.ForeignKey(Creator, on_delete=models.CASCADE, related_name='comments')
    comment_text = models.TextField(blank=True)
    comment_photo = models.ImageField(blank=True, upload_to='comment/%Y/%m/%d', verbose_name="댓글 첨부 사진")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment_text + ' '+ self.created_at.strftime("%Y-%m-%d %H:%M:%S")

class Recomment(models.Model):
    parent = models.ForeignKey(Comment, on_delete=models.CASCADE)
    writer = models.ForeignKey(Member, on_delete=models.CASCADE)
    recomment_text = models.CharField(max_length=100,blank=True)
    recomment_photo = models.ImageField(blank=True, upload_to='recomment/%Y/%m/%d', verbose_name="댓글 첨부 사진")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.recomment_text + ' '+ self.created_at.strftime("%Y-%m-%d %H:%M:%S")

comment/forms.py
from django import forms
from .models import Comment, Recomment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text','comment_photo',]

        widgets = {
            'comment_text': forms.TextInput(
                attrs={'class': 'form-control', 'style': 'width: 80%', 'style': 'margin:0 auto',
                       'placeholder': '댓글을 입력하세요'}
            ),

        }
        labels = {
            'comment_text': '',
            'comment_photo': '',
        }

class RecommentForm(forms.ModelForm):
    class Meta:
        model = Recomment
        fields = ['recomment_text','recomment_photo',]
        
        widgets = {
            'recomment_text': forms.TextInput(
                attrs={'class': 'form-control', 'style': 'width: 80%', 'style': 'margin:0 auto',
                    'placeholder': '대댓글을 입력하세요'}
            ),

        }
        labels = {
            'recomment_text': '',
            'recomment_photo': '',
        }

comment/views.py
from django.shortcuts import redirect,render,get_object_or_404
from django.urls import reverse
from .models import Comment, Recomment
from .forms import CommentForm, RecommentForm
from login.models import Creator, Member
from event.models import Event
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# @login_required
@csrf_exempt
def comment_detail(request, pk): # 댓글 보여주기
    # ajax
    # receive_comment = request.POST.get('comment',None)

    creator = Creator.objects.get(pk=pk)
    comments = creator.comments.all()

    print('get시작') 
    comment_form = CommentForm()
    recomment_form = RecommentForm()
    print('ctx반환직전')
    ctx = {
        'creator':creator,
        'comments':comments,
        'comment_form':comment_form,
        'recomment_form':recomment_form,
    }
    return render(request, 'comment/comment_detail.html', ctx)

@login_required
@csrf_exempt
def comment_create_ajax(request, pk): # 댓글 생성하기
    # is_ajax : ajax 기능에 의해 호출된 것인지 구분하기 위한 값
    is_ajax = request.POST.get('is_ajax')

    creator = Creator.objects.get(pk=pk)
    comment_form = CommentForm(request.POST, request.FILES)
    recomment_form = RecommentForm(request.POST, request.FILES)
    recomment = recomment_form.save(commit=False)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.member = request.user
        comment.creator = creator
        comment.save()
            
    if is_ajax:
        # 데이터 만들어서 던져주기
        html = render_to_string('comment/comment_create.html',{'comment':comment, 'username':request.user, 'recomment_form':recomment_form, 'recomment':recomment})
        return JsonResponse({'html':html})
    return redirect(reverse('event:comment_detail', args=[pk]))

        # if self.request.is_ajax():
        #     print('ajax request')   #ajax요청일때는 jsonresponse로 응답!
        #     return JsonResponse({
        #         'id': comment.id,
        #         #  'message': comment.message,
        #         #  'updated_at': comment.updated_at,
        #         #  'edit_url': resolve_url('blog:comment_edit', comment.post.pk, comment.pk),
        #         #  'delete_url': resolve_url('blog:comment_delete', comment.post.pk, comment.pk),
        #         }) 
        # return response


def recomment_detail(request, comment_id): # 대댓글 보여주기
    comment = Comment.objects.get(pk=comment_id)
    creator = comment.creator
    recomment_form = RecommentForm()
    ctx = {
        'comment':comment,
        'creator':creator,
        'recomment_form':recomment_form,
    }
    return render(request, 'comment/comment_detail.html', ctx)

@login_required
@csrf_exempt
def recomment_create_ajax(request, comment_id): # 대댓글 생성하기
    # is_ajax : ajax 기능에 의해 호출된 것인지 구분하기 위한 값
    is_ajax2 = request.POST.get('is_ajax2')
    print(is_ajax2)
    comment = Comment.objects.get(pk=comment_id)
    creator = comment.creator
    recomment_form = RecommentForm(request.POST, request.FILES)
    if recomment_form.is_valid():
        recomment = recomment_form.save(commit=False)
        recomment.parent = comment
        recomment.writer = request.user
        recomment.save()
        
    if is_ajax2:
        print("ajax성공")
        html = render_to_string('comment/recomment_create.html',{'recomment':recomment, 'username':request.user})
        return JsonResponse({'html':html})
    else:
        print("ajax실패")
    return redirect(reverse('comment:recomment_detail', args=[comment_id]))


# @login_required
def comment_update(request, comment_id): # 댓글 수정하기
    comment = Comment.objects.get(pk=comment_id)
    creator = comment.creator

    if request.method =='POST':
        comment_form = CommentForm(request.POST, request.FILES, instance=comment)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.member = request.user
            comment.creator = creator
            comment.save()
            url = reverse('comment:comment_detail', kwargs={'pk':comment_id})
            return redirect(to=url)
    else:
        comment_form = CommentForm(instance=comment)

    return render(request, 'comment/comment_detail.html', {'comment_form':comment_form})


def comment_delete(request, comment_id):
    is_ajax = request.GET.get('is_ajax') if 'is_ajax' in request.GET else request.POST.get('is_ajax',False)
    comment = get_object_or_404(Comment, pk=comment_id)
    creator = comment.creator

    if is_ajax:
        print("ajax 성공")
        comment.delete()
        return JsonResponse({"works":True})

    if request.method == "POST":
        print('post 시작')
        comment.delete()
        return redirect(creator)
    else:
        print('get')
        return render(request, 'comment/comment_detail.html', {'object': comment})


def recomment_delete(request, recomment_id):
    is_ajax = request.GET.get('is_ajax') if 'is_ajax' in request.GET else request.POST.get('is_ajax',False)

    recomment = get_object_or_404(Recomment, pk=recomment_id)
    comment = get_object_or_404(Comment, pk=recomment.parent.pk)
    creator = comment.creator

    if is_ajax:
        print("ajax 성공")
        recomment.delete()
        print('삭제')
        return JsonResponse({"works":True})

    if request.method == "POST":
        print('post 시작')
        recomment.delete()
        return redirect(creator)
    else:
        print('get')
        return render(request, 'comment/comment_detail.html', {'object': recomment} )

comment/templates/comment/comment_create.html
<div class="single_comment">
    <div class='row flex-container'>
        <div id="content" class='flex-item'><b>'{{ comment.member.nickname }}'님 :</b> <span id='comment_text_{{comment.pk}}'>{{ comment.comment_text }}</span> </div>
        <div id="del_btn" class='flex-item-gnb'>
            {% if comment.member == username %} <!-- 댓글작성자:{{comment.member}} , 접속자:{{username}}-->
                {% comment %} <a href="{% url 'comment:comment_update' comment.id %}" class="btn btn-warning btn-sm btn_comment_update">수정</a> {% endcomment %}
                <a href="{% url 'comment:comment_delete' comment.id %}" class="btn btn-sm btn-outline-success btn_comment_delete">삭제</a>
            {% elif comment.member == request.user %}
                {% comment %} <a href="{% url 'comment:comment_update' comment.id %}" class="btn btn-warning btn-sm btn_comment_update">수정</a> {% endcomment %}
                <a href="{% url 'comment:comment_delete' comment.id %}" class="btn btn-sm btn-outline-success btn_comment_delete">삭제</a>
            {% endif %}
        </div>
    </div>
    {% if comment.comment_photo %}
    <div class='row'><img src="{{comment.comment_photo.url}}" style='max-width:300px' id="comment_photo_{{comment.pk}}"></div>
    {% endif %}
    <div class='row' id='create_at'><small>{{comment.created_at}}</small></div>
    <div class='row recomment_area'>
        <button id='recomment_btn_{{comment.id}}' class="btn btn-outline-success btn-sm">대댓글</button>
      
        <div class='row recomment_form' id='recomment_form_{{comment.id}}'>
            <div class="container recomment_list" id="recomment_list_{{comment.id}}">
            {% for recomment in comment.recomment_set.all %}
                {% include 'comment/recomment_create.html' %}
            {% endfor %}
            </div>

            <div class="container recomment_submit">
                {% comment %} <div id="comment_pk_section" type='hidden'>{{comment.pk}}</div> {% endcomment %}
                <form class='row' action="{% url 'comment:recomment_create_ajax' comment.id %}" enctype='multipart/form-data' method='POST' id="recommentForm_{{comment.pk}}">
                    {% csrf_token %}
                    <input type="hidden" name='is_ajax2' value=''>
                    <div class="col-md-7 col-sm-12">{{ recomment_form.recomment_text }}</div>
                    <div class="col-md-4 col-sm-12">{{ recomment_form.recomment_photo }}</div>
                    <div class="col-md-1 col-sm-12"><input type="submit" class="btn btn-primary" value='OK' id='recomment_submit_btn'></div>
                </form>
                <div class="fold_row row"><button id="recomment_fold_{{comment.id}}" class='btn btn-outline-success btn-sm'>접기</button></div>
            </div>
        </div>

    </div>
    <hr>
</div>

<script>
    $("#comment_list").scrollTop($("#comment_list")[0].scrollHeight);

    let recobtn_{{comment.id}} = $('#recomment_btn_{{comment.id}}')
    let fold_btn_{{comment.id}} = $('#recomment_fold_{{comment.id}}')
    
    $('#recomment_form_{{comment.id}}').hide()
    recobtn_{{comment.id}}.click(function(){
        $('#recomment_form_{{comment.id}}').toggle()
    })
    
    fold_btn_{{comment.id}}.click(function(){
    $('#recomment_form_{{comment.id}}').hide()
    })
    
    
</script>
<script>
// 대댓글 작성
    $('#recommentForm_{{comment.pk}}').submit(function(e){
        e.preventDefault()
        e.stopPropagation()

        $('input[name="is_ajax2"]').val("1");

        url = $(this).attr('action');
        var formData = new FormData(this);

        $.ajax({
            url:url,
            method:"POST",
            data:formData,
            processData: false,
            contentType: false,

        }).done(function(data) {
            $('#recomment_list_{{comment.id}}').append(data.html);
            // is_ajax2 값 초기화
            $('#recommentForm_{{comment.pk}} input[name="is_ajax2"]').val("");
            $('#recommentForm_{{comment.pk}} #id_recomment_text').val("");
            $('#recommentForm_{{comment.pk}} #id_recomment_photo').val("");
        })
        return false;
    });
</script>

<script>
// 대댓글 삭제
$('.btn_recomment_delete_{{comment.pk}}').click(function(e) {
    e.preventDefault();
    var input = confirm('대댓글을 삭제하시겠습니까?');
    if (input==true) {
        alert('대댓글을 삭제하였습니다.');
        recomment = $(this).parents('#single_recomment');
        url = $(this).attr('href')+"?is_ajax=1"; // ajax 호출임을 구분할 수 있게 값 추가
        $.ajax({
            url:url
        }).done(function(data) {
            if (data.works) {
                console.log(recomment)
                recomment.remove(); // 해당 객체 지우기
            }
        });
    }
});
</script>
{% comment %} <script src="{% static 'comment/js/create2.js' %}"></script> {% endcomment %}


    

comment/templates/comment/comment_detail.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style %}
    <link rel="stylesheet" href="{% static 'comment/css/comment.css' %}">
{% endblock %}


{% block main %}
<div class="signup_title" style="margin-top: 50px; text-align: center;">
    <h1>Visitor Book</h1><br>
</div>

<div class="container" id='comment_list' class="custom-scrollbar-js p-2">  
    {% for comment in comments %}
        {% include 'comment/comment_create.html' %}

    {% endfor %}
    

        
</div>
    <hr>
<div class="container">
    <div class="col comment_submit">
    <form class="row" method="POST" action="{% url 'event:comment_create_ajax' creator.pk %}" enctype='multipart/form-data' id='comment_form'>
        {% csrf_token %}
        <input type="hidden" name='is_ajax' value=''>
        <input type="hidden" name='comment_writer' value='{{request.user.pk}}'>
        <div class="col-md-7 col-sm-12">{{ comment_form.comment_text }}</div>
        <div class="col-md-4 col-sm-12">{{ comment_form.comment_photo }}</div>
        <div class='col-md-1 col-sm-12'><input type="submit" class="btn btn-primary" value='댓글 입력' id='comment_submit_btn' ></div>
        <button class="goback"><a href="{% url 'event:creator_detail' creator.pk %}">뒤로가기</a></button>
        <br>
    </form>
    <br/>
    </div>
</div>
<br/>
{% endblock %}

{% block injiscript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'comment/js/create.js' %}"></script>

{% endblock %}

comment/templates/comment/recomment_create.html
<div id="single_recomment">
     <div class='row flex-container single-recomment' >
        <div class="flex-item">
            <b>'{{ recomment.writer.nickname }}'님 : </b> <span>{{ recomment.recomment_text }}</span>
        </div>
        <div class="flex-item-gnb">
            {% if recomment.writer == username %}
                <a href="{% url 'comment:recomment_delete' recomment.id %}" class="btn btn-sm btn-outline-success btn_recomment_delete_{{comment.pk}}">삭제</a>
            {% elif recomment.writer == request.user %}
                <a href="{% url 'comment:recomment_delete' recomment.id %}" class="btn btn-sm btn-outline-success btn_recomment_delete_{{comment.pk}}">삭제</a>
            {% endif %}  
        </div>
    </div>
        {% if recomment.recomment_photo %}
        <div class='row'><img src="{{recomment.recomment_photo.url}}" style='max-width:300px'></div>
        {% endif %}
        <div class='row' id='create_at'><small>{{recomment.created_at}}</small></div>
<hr>
</div>