login/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'login'

urlpatterns = [
    path('', views.main, name='main'),
    path('login/', views.login, name='login'), # 로그인 전체화면
    path('signup/', views.signup_general, name='signup_general'), # 회원가입 전체화면
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('login/<int:pk>/sign_up/', views.signup, name='signup'), # 소셜 로그인 추가 정보 입력
    path('login/<int:pk>/update/', views.login_update, name='update'), # 사용자 정보 수정
    path('login/<int:pk>/', views.mypage, name='mypage'), # 사용자 마이페이지
    path('login/<int:pk>/delete/', views.user_delete, name='delete'), # 로그인 계정 삭제

    path('login/create_creator/', views.create_creator, name="create_creator"), # 크리에이터 등록
    path('login/<int:pk>/creator/', views.creator_mypage, name='creator_mypage'), # 크리에이터 마이페이지
    path('login/<int:pk>/creator/update/', views.creator_update, name='creator_update'), # 크리에이터 정보 수정
    path('login/<int:pk>/creator_delete/', views.creator_delete, name='creator_delete'),  # 크리에이터 계정 삭제
    path('login/<int:pk>/event/update/', views.event_update, name='event_update'), # 크리에이터 이벤트 수정
    # path('login/<int:pk>/creator/delete/', views.creator_delete, name='creator_delete'), -> 이렇게 하면 삭제하고 나서 새로고침했을 때 delete url을 계속 유지해서 오류 뜸


    path('login/signup_form/', views.signup_form, name="signup_form"), # 일반 회원가입 폼
    path('login/login_form/', views.login_form, name="login_form"), # 일반 로그인 폼

    path('login/check_id/', views.id_overlap_check, name='id_overlap_check'),  # id 중복 체크
    path('login/check_nickname/', views.nickname_lap_check, name='nickname_lap_check'),  # nickname 중복 체크
    path('login/check_email/', views.email_lap_check, name='email_lap_check'),  # email 중복 체크

    path('creator/like/', views.like, name="like_creator"), #크리에이터 좋아요/구독
]

login/templates/login/creator_mypage.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style %}
<link rel="stylesheet" href="{% static 'login/creator.css' %}">
{% endblock %}

{% block main %}
<div class="mypage_title">
    <h2>Creator page</h2>
    <p>나의 크리에이터 정보를 확인할 수 있습니다.</p>
</div>
<div class="contents">
    <table class="additional_info">
        <tr>
            <td><b>크리에이터명</b></td>
            <td>{{ creator.creator_name }}</td>
        </tr>
        <tr>
            <td><b>크리에이터 사진</b></td>
            <!--            <td>{{ creator.creator_photo }}</td>-->
            <td><img src="{{ creator.creator_photo.url }}" alt="creator photo"></td>
        </tr>
        <tr>
            <td><b>개인/팀 소개</b></td>
            <td>{{ creator.desc }}</td>
        </tr>
    </table>



    <button type="button">
        <a href="{% url 'login:creator_update' creator.pk %}">수정하기</a>
    </button>
    <button type="button">
        <a href="{% url 'login:main' %}">메인으로</a>
    </button>
    <button type="button">
        <a href="{% url 'event:event_register' %}">이벤트 등록</a>
    </button>
    <br/><br/>
    <hr/>

</div>
<h1>내 이벤트 한 눈에 보기</h1>
<h5>각 이벤트를 수정하거나 삭제할 수 있습니다</h5>
<br><br><br>
<div class="row" id="event_row">
    {% for event in events %}
            <div class="col-12 col-md-6" id="event_info">
                <tr>
                    <td><h3>{{ event.event_name }}</h3></td>
                </tr>
                <hr>
                <tr>
                    <td><b>장르</b></td>
                    <td>{{ event.get_genre_display }}</td>
                </tr>
                <br>
                <tr>
                    <td><b>이벤트 장소</b></td>
                    <td>{{ event.location.city }} {{ event.location.gu }} {{ event.location.rest_address }}</td>
                </tr>
                <br><br>
                <tr>
                    <td><b>시작 시간</b></td>
                    <td>{{ event.start_date_time }}</td>
                </tr>
                <br>
                <tr>
                    <td><b>종료 시간</b></td>
                    <td>{{ event.end_date_time }}</td>
                </tr>
                <br><br>
                <tr>
                    <td>
                        <img src="{{ event.eventimage_set.all.first.image.url }}" class="event_img" alt="event photo">
                    </td>
                </tr>
                <hr>
                    <a href="{% url 'event:event_delete' event.pk %}" >
                        <button type="button" class="event_delete_btn" id="delete_event">
                            삭제하기
                        </button>
                    </a>
                    <a href="{% url 'login:event_update' event.pk %}">
                        <button type="button" id="event_btn">수정하기
                        </button>    
                        </a>                
                    </div>
                {% endfor %}
        </div>
    <!-- </div> -->
</div>
<br/>
<hr/>
<div id="user_pk_section" style="display:none">{{user.pk}}</div>
<div class="delete_creator">
    <a href="{% url 'login:creator_delete' user.pk %}" id="delete_creator">
        <button type="button" class="delete_btn">
            크리에이터 계정 삭제
        </button>
    </a>
</div>
{% endblock %}

{% block hanseokscript %}
<script>
    // let user_pk_tag = document.querySelector('#user_pk_section')
    // let user_pk = user_pk_tag.textContent
    // let returnUrl = '/login/' + user_pk + '/creator/'

    let delete_creator = document.querySelector('#delete_creator')

    delete_creator.onclick = function (e) {
        let confirm_result = confirm("정말 크리에이터를 지우시겠습니까?\n※주의※ 되돌릴 수 없습니다.");
        if (confirm_result === false) {
            //return true
            //document.querySelector('#delete_creator').setAttribute('href', returnUrl)
            e.preventDefault()   //이게 더 많이 쓰이는 방법이라고 함.
        }
    }

    // let delete_event = Array.from(document.querySelectorAll('.event_delete_btn'))
    // let confirm_result = confirm('정말 이벤트를 지우시겠습니까?\n※주의※ 되돌릴 수 없습니다.');

    // for(let i=0; i<delete_event[i].length;i++){
    //     delete_event[i].addEventListener('click',function(e){
    //         confirm_result
    //         e.preventDefault()
    //         console.log(e)
    // })
    let delete_event = document.querySelector('#delete_event')

    delete_event.onclick = function (e) {
        let confirm_result = confirm('정말 이벤트를 지우시겠습니까?\n※주의※ 되돌릴 수 없습니다.');
        if (confirm_result === false) {
            e.preventDefault()
        }
    }

</script>
{% endblock %}

login/templates/login/login.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}
{% providers_media_js %}

{% block main %}
<div class="content" style="margin: 50px auto; border: 1px solid lightgray;  width: 600px; border-radius: 30px;">
    <!--    <div class="shadow p-3 mb-5 bg-white rounded"-->
    <!--         style="margin: 0 auto; text-align: center; margin-top: 50px; width: 500px; height: 60px; border: 1px solid #0080ff; background-color: #0080ff!important; border-radius: 10px;">-->
    <!--        <a href="/accounts/signup" style="text-decoration: none; color: white;">회원가입</a>-->
    <!--        <br>-->
    <!--    </div>-->
    <!--    <hr/>-->
    {% if user.is_authenticated %}
    <br>
    {% if user.nickname == '' %}
    <meta http-equiv="refresh" content="0.1;url={% url 'login:signup' user.pk %}"/>
    <!--    <p style="text-align: center">더 편리한 서비스를 위해 추가 정보를 입력하세요</p>-->
    <!--    <div class="shadow p-3 mb-5 bg-white rounded"-->
    <!--         style="margin: 0 auto; text-align: center; width: 500px; height: 60px;"><a href="{% url 'login:signup' user.pk %}">signup</a>-->
    <!--    </div>-->
    {% else %}
    <p style="font-weight: 700; text-align: center;">{{ user.nickname }} 님 안녕하세요</p>
    <div class="shadow p-3 mb-5 bg-white rounded"
         style="margin: 0 auto; text-align: center; width: 500px; height: 60px;"><a
            href="{% url 'login:mypage' user.pk %}">My page</a></div>
    <br/>
    <div class="shadow p-3 mb-5 bg-white rounded"
         style="margin: 0 auto; text-align: center; width: 500px; height: 60px;"><a href="/accounts/logout">로그아웃</a>
    </div>
    {% endif %}

    {% else %}
    <br/>
    <br/>
    <div class="shadow p-3 mb-5 bg-white rounded"
         style="margin: 0 auto; text-align: center; width: 500px; height: 60px; background-color: white!important; border-radius: 10px;">
        <a href="{% url 'login:login_form' %}" style="color: black;">일반 계정으로
            로그인하기</a>
    </div>

    <div class="shadow p-3 mb-5 bg-white rounded"
         style="margin: 0 auto; text-align: center; width: 500px; height: 60px; background-color: white!important; border-radius: 10px;">
        <a href="{% provider_login_url 'google' %}" style="color: black;"><img src="/static/img/google.jpg"
                                                                               alt="google"
                                                                               style="height: 40px; width: 40px; margin-right: 10px;">구글로
            로그인하기</a>
    </div>
    <div class="shadow p-3 mb-5 bg-white rounded"
         style="margin: 0 auto; text-align: center; width: 500px; height: 60px; background-color: white!important; border-radius: 10px;">
        <a href="{% provider_login_url 'naver' %}" style="color: black;"><img src="/static/img/naver.png" alt="kakao"
                                                                              style="height:30px; width: 30px; margin-right: 10px; ">네이버로
            로그인하기</a>
    </div>
    <hr/>
    <div style="text-align: center;">
        <b>혹시 아직 회원이 아니신가요?</b> <br/>
        <br/>
        <a href="{% url 'login:signup_general' %}">회원가입</a>
    </div>
    {% endif %}
<br/>

</div>
{% endblock %}

login/templates/login/login_form.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style %}
<link rel="stylesheet" href="{% static 'login/login_form.css' %}">
{% endblock %}

{% block main %}
<div class="signup_title" style="margin-top: 50px; text-align: center;">
    <h3 style="color: #dd445b ;">Login</h3>
    <p></p>
</div>
<div class="signup_form" style="margin-bottom: 100px;">
    <form method="post" enctype="multipart/form-data" autocomplete="off" style="margin: 0 auto;">
        {% csrf_token %}
        <table class="additional_info">
            <tr>
                <td>아이디</td>
                <td><input type="text" name="username" placeholder="아이디를 입력해주세요"
                           value="{{user.username}}" required/></td>
            </tr>
            <tr>
                <td>비밀번호</td>
                <td><input type="password" name="password" placeholder="비밀번호를 입력해주세요"
                           required minlength="4" value="{{user.password}}"/></td>
            </tr>
        </table>
        <button type="submit">
            로그인
        </button>

        <button type='button'>
            <a href="{% url 'login:signup_general' %}">회원가입</a>
        </button>
    </form>
</div>

{% endblock %}

login/templates/login/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style %}
<link rel="stylesheet" href="{% static 'login/mypage.css' %}">
{% endblock %}

{% block main %}
<div class="signup_title" style="margin-top: 50px; text-align: center;">
    <h2 style="color: #dd445b ;">My page</h2>
    <p>나의 프로필 정보를 확인할 수 있습니다</p>
</div>
<br/>
<div class="row contents-container" style="text-align: center; margin: 0 auto;">
    <div class="col-12 col-md-6 login-table">
        {% if user.nickname == '' %}
        <b>설정된 닉네임이 없습니다.</b>
        <b>수정하기를 눌러 설정해주세요!</b>
        {% else %}

    <table class="type03">
        <!--            <tr>-->
        <!--                <th scope="row">가입 유형</th>-->
        <!--                <td>{{ user.username }}</td>-->
        <!--            </tr>-->
        <tr>
            <th scope="row">아이디</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th scope="row">닉네임</th>
            <td>{{ user.nickname }}</td>
        </tr>
        <tr>
            <th scope="row">선호지역</th>
            <td>{{ user.city }} {{ user.gu }}</td>
        </tr>
        <tr>
            <th scope="row">가입 날짜</th>
            <td>{{ user.created_on }}</td>
        </tr>
    </table>
    {% endif %}
    <!--        <p><b>닉네임</b> {{ user.nickname }}</p>-->

        <!--        <b>선호 지역 : {{ user.city }} {{ user.gu }}</b>-->
        <!--        <p>이메일: {{ user.email }}</p>-->
        <!--        <p>가입 날짜: {{ user.created_on }}</p>-->
    </div>
    <div class="col-12 col-md-6 creators-events-list">
        <div class="row creator_list">
            <h5>LIKE 크리에이터</h5>
            <br/><br/>
            {% if like_creators.count == 0 %}
                <div class="col-12 creator">
                    <p>좋아하는 크리에이터가 없어요</p>
                </div>
            {% else %}
                {% for creator in like_creators.all %}
                    <div class="col-12 creator">
                        <div id="creator_info">
                            <div class="image">
                                <img src="{{ creator.creator_photo.url }}">
                            </div>
                            <div class="name">
                                <a href="{% url "event:creator_detail"  creator.events.first.id %}">
                                    {{ creator.creator_name }}
                                </a>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            {% endif %}
        </div>
        <div class="row event_list">
            <h5>LIKE 크리에이터의 이벤트 현황</h5>
            <br/><br/>
            {% if events.count == 0 %}
                <div class="col-12 event">
                    진행 중인 이벤트가 없어요!
                </div>
            {% else %}
                {% for event in events %}
                    <div class="col-12 event">
                        <a href="{% url "event:creator_detail"  event.id %}">
                            {{ event.event_name }}
                            <div id="processing">진행중</div> - {{ event.creator.creator_name }}
                        </a>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

    </div>
</div>

<div class="buttons-container">
    <div class="item">
        <button type="button">
            <a href="{% url 'login:update' user.pk %}">수정하기</a>
        </button>
    </div>
<!--    <div class="item">-->
<!--        <button type="button">-->
<!--            <a href="{% url 'login:main' %}">메인으로</a>-->
<!--        </button>-->
<!--    </div>-->
    <div class="item">
        {% if creators is None %}
        <button type="button" style="width: 140px!important;">
            <a href="{% url 'login:create_creator' %}">크리에이터 등록</a>
        </button>
        {% else %}
        <button type="button" style="width: 140px!important;">
            <a href="{% url 'login:creator_mypage' user.pk %}">크리에이터 페이지</a>
        </button>
        {% endif %}
    </div>
</div>
    <br/>
    <div class="delete-container">
        <div id="user_pk_section" style="display:none">{{user.pk}}</div>
<!--        <div class="logout">-->
<!--            <a href="/accounts/logout" id='logout_btn'>로그아웃</a>-->
<!--        </div>-->
        <button type="button"><div class="delete_account">
            <a href="{% url 'login:delete' user.pk %}" id="delete_btn">계정 삭제</a>
        </div></button>
    </div>
    <br/><br/><br/>

{% endblock %}

{% block hanseokscript %}
<script>
    let user_pk_tag = document.querySelector('#user_pk_section')
    let user_pk = user_pk_tag.textContent
    let returnUrl = '/login/' + user_pk

    let delete_btn = document.querySelector('#delete_btn')
    // delete_btn.addEventListener('click', function () {
    //    confirm('정말 계정을 삭제하시겠습니까?\n확인을 누르면 되돌릴 수 없습니다!')
    // }) 

    delete_btn.onclick = function() {
        let confirm_result = confirm("정말 계정을 삭제하시겠습니까?\n되돌릴 수 없습니다.");
        if (confirm_result === false) {
            document.querySelector('#delete_btn').setAttribute('href', returnUrl)
        }
    }

    let logout_btn = document.querySelector('#logout_btn')
    // logout_btn.addEventListener('click', function () {
    //  confirm('로그아웃 하시겠습니까?')

    logout_btn.onclick = function() {
        let confirm_result = confirm("로그아웃을 하시겠습니까?");   
        if(confirm_result === false){
            document.querySelector('#logout_btn').setAttribute('href',returnUrl)
        } 
    }

</script>
{% endblock %}

login/templates/login/signup.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}
{% providers_media_js %}

{% block main %}
<div class="content" style="margin: 50px auto; border: 1px solid lightgray;  width: 600px; border-radius: 30px;">
    <!--    <div class="shadow p-3 mb-5 bg-white rounded"-->
    <!--         style="margin: 0 auto; text-align: center; margin-top: 50px; width: 500px; height: 60px; border: 1px solid #0080ff; background-color: #0080ff!important; border-radius: 10px;">-->
    <!--        <a href="/accounts/signup" style="text-decoration: none; color: white;">회원가입</a>-->
    <!--        <br>-->
    <!--    </div>-->
    <!--    <hr/>-->
    <br/><br/>
    <div class="shadow p-3 mb-5 bg-white rounded"
         style="margin: 0 auto; text-align: center; width: 500px; height: 60px; background-color: white!important; border-radius: 10px;">
        <a href="{% url 'login:signup_form' %}" style="color: black;">일반 계정으로
            회원가입하기</a>
    </div>

    <div class="shadow p-3 mb-5 bg-white rounded"
         style="margin: 0 auto; text-align: center; width: 500px; height: 60px; background-color: white!important; border-radius: 10px;">
        <a href="{% provider_login_url 'google' %}" style="color: black;"><img src="/static/img/google.jpg"
                                                                               alt="google"
                                                                               style="height: 40px; width: 40px; margin-right: 10px;">구글로
            회원가입하기</a>
    </div>
    <div class="shadow p-3 mb-5 bg-white rounded"
         style="margin: 0 auto; text-align: center; width: 500px; height: 60px; background-color: white!important; border-radius: 10px;">
        <a href="{% provider_login_url 'naver' %}" style="color: black;"><img src="/static/img/naver.png" alt="kakao"
                                                                              style="height:30px; width: 30px; margin-right: 10px; ">네이버로
            회원가입하기</a>
    </div>
    <hr/>
    <div style="text-align: center;">
        <b>이미 회원이신가요?</b> <br/>
        <br/>
        <a href="{% url 'login:login' %}">로그인</a>
    </div>
    <br/>

</div>
{% endblock %}

login/templates/login/signup_form.html
{% extends 'base.html' %}
{% load static %}

{% block custom_style %}
    <link rel="stylesheet" href="{% static 'login/signup_form.css' %}">
{% endblock %}

{% block main %}
<div class="signup_title" style="margin-top: 50px; text-align: center;">
    <h3 style="color: #dd445b;">Sign up</h3>
    <p>아래 정보를 입력하시면 가입이 완료됩니다</p>
</div>
<div class="signup_form" style="margin-bottom: 100px;">
    <form method="post" enctype="multipart/form-data" autocomplete="off" style="margin: 0 auto;">
        {% csrf_token %}
        <table class="additional_info">
            <tr>
                <td>아이디</td>
<!--                <td><input type="text" name="username" value="{{user.username}}" required-->
<!--                placeholder="아이디를 입력해주세요"/></td>-->
                <td><input type="text" class="username_input" name="username" check_result="fail" required
                minlength="4" maxlength="12" value="{{user.username}}" placeholder="4~12자의 영문 대소문자와 숫자로만 입력"/>
                <button type="button" class="id_overlap_button" onclick="id_overlap_check()"
                >Check!</button>
                <img src="/static/img/green_check.png" id="id_check_success" class="check_box"
                 ></td>
            </tr>
            <tr>
                <td>비밀번호</td>
                <td><input type="password" name="password1" value="{{user.password}}" required
                placeholder="비밀번호를 입력해주세요" required minlength="4"/></td>
            </tr>
            <tr>
                <td>비밀번호 확인</td>
                <td><input type="password" name="password2" required
                placeholder="위와 동일하게 입력해주세요" required minlength="4"/></td>
            </tr>
            <tr>
                <td>닉네임</td>
                <td><input type="text" class="nickname_input" check_result="fail" name="nickname" value="{{user.nickname}}"
                required minlength="2" maxlength="12" placeholder="닉네임을 입력해주세요"/>
                <button type="button" class="nickname_lap_button" onclick="nickname_lap_check()"
                >Check!</button>
                <img src="/static/img/green_check.png" id="nickname_check_success" class="check_box"
                > </td>           
            </tr>
            <tr>
                <td>이메일</td>
                <td><input type="email" class="email_input" check_result="fail" name="email" value="{{user.email}}"
                required placeholder="이메일을 입력해주세요"/>
                <button type="button" class="email_lap_button" onclick="email_lap_check()">Check!</button>
                <img src="/static/img/green_check.png" id="email_check_success" class="check_box">
                </td>
            </tr>
            <tr>
                <td>선호도시</td>
                <td>
                    <select
                            name="city"
                            id="city"
                            onchange="addressKindChange(this)"
                            class="selected_city"
                    >
                        <option>도시를 선택해주세요</option>
                        <option value="서울특별시">서울특별시</option>
                    </select>
                </div>
                </td>
            <tr/>
            <tr>
                <td>선호구</td>
                <div class="choose_gu" style="margin-top: 1rem;">
                    <td>
<!--                        <label for="gu">구 선택</label>-->
                        <select name="gu" id="gu" class="selected_gu">
                            <option>구를 선택해주세요</option>
                        </select>
                </div>
                </td>
            </tr>
        </table>
        <button type="submit" class="submit_btn">
            회원가입
        </button>
    </form>
</div>

{% endblock %}


{% block hanseokscript %}
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<!--jquery사용하려면 필요한 스크립트 코드  (메서드 사용 가능하게 해줌)-->
<script>
    function id_overlap_check() {
//  아이디 중복 확인
        $('.username_input').change(function () {
            $('#id_check_success').hide();
            $('.id_overlap_button').show();
            $('.username_input').attr('check_result', "fail");
        })

        if ($('.username_input').val() == '') {
            alert('아이디를 입력해주세요')
            return;
        }


        id_overlap_input = document.querySelector('input[name="username"]');

        $.ajax({
            url: "{% url 'login:id_overlap_check' %}",
            // type: "POST",
            data: {
                'username': id_overlap_input.value
            },
            datatype: 'json',
            success: function (data) {
                console.log(data['overlap']);
                if (data['overlap'] == "fail") {
                    alert("이미 존재하는 아이디입니다");
                    id_overlap_input.focus();
                    document.querySelector('.submit_btn').setAttribute('disabled', true);
                    return;
                } else {
                    alert('사용가능한 아이디입니다');
                    $('.username_input').attr('check_result', "success");
                    $("#id_check_success").show();
                    $('.id_overlap_button').hide();
                    document.querySelector('.submit_btn').removeAttribute('disabled');
                    return;
                }
            }
        });
    }

    function nickname_lap_check() {
        // 닉네임 중복 확인
        $('.nickname_input').change(function () {
            $('#nickname_check_success').hide();
            $('.nickname_lap_button').show();
            $('.nickname_input').attr('check_result', "fail");
        })

        if ($('.nickname_input').val() == '') {
            alert('닉네임을 입력해주세요')
            return;
        }

        nickname_lap_input = document.querySelector('input[name="nickname"]');

        $.ajax({
            url: "{% url 'login:nickname_lap_check' %}",
            // type: "POST",
            data: {
                'nickname': nickname_lap_input.value
            },
            datatype: 'json',
            success: function (data) {
                console.log(data['overlap']);
                if (data['lap'] == "fail") {
                    alert("이미 존재하는 닉네임입니다");
                    nickname_lap_input.focus();
                    document.querySelector('.submit_btn').setAttribute('disabled', true);
                    return;
                } else {
                    alert('사용가능한 닉네임입니다');
                    $('.nickname_input').attr('check_result', "success");
                    $("#nickname_check_success").show();
                    $('.nickname_lap_button').hide();
                    document.querySelector('.submit_btn').removeAttribute('disabled');
                    return;
                }
            }
        });
        }

    function email_lap_check() {
        // 닉네임 중복 확인
        $('.email_input').change(function () {
            $('#email_check_success').hide();
            $('.email_lap_button').show();
            $('.email_input').attr('check_result', "fail");
        })

        if ($('.email_input').val() == '') {
            alert('이메일을 입력해주세요')
            return;
        }

        email_lap_input = document.querySelector('input[name="email"]');

        $.ajax({
            url: "{% url 'login:email_lap_check' %}",
            // type: "POST",
            data: {
                'email': email_lap_input.value
            },
            datatype: 'json',
            success: function (data) {
                console.log(data['overlap']);
                if (data['lap'] == "fail") {
                    alert("이미 존재하는 이메일입니다");
                    email_lap_input.focus();
                    document.querySelector('.submit_btn').setAttribute('disabled', true);
                    return;
                } else {
                    alert('사용가능한 이메일입니다');
                    $('.email_input').attr('check_result', "success");
                    $("#email_check_success").show();
                    $('.email_lap_button').hide();
                    document.querySelector('.submit_btn').removeAttribute('disabled');
                    return;
                }
            }
        });
        }


    function addressKindChange(e) {
        let city;
        let seoul = [
            "강남구",
            "송파구",
            "서초구",
            "강동구",
            "관악구",
            "영등포구",
            "강서구",
            "양천구",
            "구로구",
            "금천구",
            "종로구",
            "중구",
            "동대문구",
            "중랑구",
            "마포구",
            "용산구",
            "성동구",
            "광진구",
            "은평구",
            "서대문구",
            "성북구",
            "강북구",
            "도봉구",
            "노원구",
        ];
        let target = document.querySelector("#gu");

        if (e.value == "서울특별시") {
            city = seoul;
        }
        for (x in city) {
            let opt = document.createElement("option");
            opt.value = city[x];
            opt.innerHTML = city[x];
            target.appendChild(opt);
        }
    }

    let save_btn = document.querySelector('#save_btn')
    save_btn.addEventListener('click', function () {
        alert('회원가입이 완료되었습니다.')
    })
    // save_btn.onclick = function() {
    //     confirm("회원가입이 완료되었습니다.");
    // }


    //유효성 검사
    {% comment %} function validate() {
        var re = /^[a-zA-Z0-9]{4,12}$

        var id = document.getElementById("username");


        if(!check(re,id,"아이디는 4~12자의 영문 대소문자와 숫자로만 입력")) {
            alert("아이디는 4~12자의 영문 대소문자와 숫자로만 입력해주세요.")
           return false;
       }

    } {% endcomment %}

</script>


{% endblock %}