event/urls.py
from django.urls import path, include
from event import views
from comment.views import comment_detail, comment_create_ajax

app_name = 'event'

urlpatterns = [
    path('register/', views.register_event, name="event_register"),
    path('creator_event/<int:pk>/',views.creator_detail, name='creator_detail'),
    path('creator_event/<int:pk>/comment/', comment_detail, name='comment_detail'),
    path('creator_event/<int:pk>/comment/create/', comment_create_ajax, name='comment_create_ajax'),
    path('search_result/', views.search_result, name='search_result'),
    path('search_result_click/<str:tag>', views.search_result_click, name='search_result_click'),

    path('today_event/', views.today_event, name="today_event"),

    path('creator_event/<int:pk>/delete', views.event_delete, name="event_delete"),
]

helloevent/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.shortcuts import render, redirect
import login.views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
    path('location/', include('location.urls')),
    path('event/', include('event.urls'), name='event'),
    path('login/', login.views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('comment/',include('comment.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'login'

urlpatterns = [
    path('', views.main, name='main'),
    path('login/', views.login, name='login'), # 로그인 전체화면
    path('signup/', views.signup_general, name='signup_general'), # 회원가입 전체화면
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('login/<int:pk>/sign_up/', views.signup, name='signup'), # 소셜 로그인 추가 정보 입력
    path('login/<int:pk>/update/', views.login_update, name='update'), # 사용자 정보 수정
    path('login/<int:pk>/', views.mypage, name='mypage'), # 사용자 마이페이지
    path('login/<int:pk>/delete/', views.user_delete, name='delete'), # 로그인 계정 삭제

    path('login/create_creator/', views.create_creator, name="create_creator"), # 크리에이터 등록
    path('login/<int:pk>/creator/', views.creator_mypage, name='creator_mypage'), # 크리에이터 마이페이지
    path('login/<int:pk>/creator/update/', views.creator_update, name='creator_update'), # 크리에이터 정보 수정
    path('login/<int:pk>/creator_delete/', views.creator_delete, name='creator_delete'),  # 크리에이터 계정 삭제
    path('login/<int:pk>/event/update/', views.event_update, name='event_update'), # 크리에이터 이벤트 수정
    # path('login/<int:pk>/creator/delete/', views.creator_delete, name='creator_delete'), -> 이렇게 하면 삭제하고 나서 새로고침했을 때 delete url을 계속 유지해서 오류 뜸


    path('login/signup_form/', views.signup_form, name="signup_form"), # 일반 회원가입 폼
    path('login/login_form/', views.login_form, name="login_form"), # 일반 로그인 폼

    path('login/check_id/', views.id_overlap_check, name='id_overlap_check'),  # id 중복 체크
    path('login/check_nickname/', views.nickname_lap_check, name='nickname_lap_check'),  # nickname 중복 체크
    path('login/check_email/', views.email_lap_check, name='email_lap_check'),  # email 중복 체크

    path('creator/like/', views.like, name="like_creator"), #크리에이터 좋아요/구독
]

templates/base.html
<!doctype html>
{% load static %}
{% load socialaccount %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>지금 뭐하지?</title>

    <!-- <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/carousel/"> -->

    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <!--font-->
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <!--    font-family: 'Noto Sans KR', sans-serif;-->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap" rel="stylesheet">
    <!--    font-family: 'Roboto', sans-serif;-->
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap" rel="stylesheet">
    <!--    font-family: 'Nanum Pen Script', cursive;-->
    <link href="https://fonts.googleapis.com/css2?family=Black+Han+Sans&display=swap" rel="stylesheet">
    <!--    font-family: 'Black Han Sans', sans-serif;-->
    <link href="https://fonts.googleapis.com/css2?family=Do+Hyeon&display=swap" rel="stylesheet">
    <!--font-family: 'Do Hyeon', sans-serif;-->
    <link href="https://fonts.googleapis.com/css2?family=Nanum+Brush+Script&display=swap" rel="stylesheet">
    <!--    font-family: 'Nanum Brush Script', cursive;-->

    {% block custom_style %}
    {% endblock %}
</head>

<body>
    <script src={% static 'js/base.js' %}></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script> $('.carousel').carousel({interval: 2000})</script>

<div id="wrapper">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <a class="navbar-brand" href="/" style="font-family: 'Do Hyeon', sans-serif; font-size: 1.8rem;">지금 뭐하지?</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'event:today_event' %}" style="color: gray;">Today's <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'event:event_register' %}" style="color: gray;">이벤트 등록</a>
                    </li>
                </ul>
                <form class="form-inline mt-2 mt-md-0" action="{% url 'event:search_result' %}" method="get">
                    {% csrf_token %}
                    <input class="form-control mr-sm-2" type="text" placeholder="찾고 싶은 이벤트의 태그를 입력하세요"
                           aria-label="Search" name="search_data">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    <div class="nav-item">
                        <button type="button" class="user_icon" onclick="myFunction()" style="border: none; background-color: transparent;">
                            <img src="/static/img/user_icon.png" alt="user_icon.png" style="height: 40px; width:40px; background-size: 10px;">
                        </button>
                        {% if user.is_authenticated %}
                            <div class="dropdown-content" id="myDropdown" dir="rtl">
                                <a href="{% url 'login:mypage' user.pk %}">마이페이지</a><br/>
                                {% if creator is None %}
                                    <a href="{% url 'login:create_creator' %}">크리에이터 페이지</a><br/>
                                {% else %}
                                    <a href="{% url 'login:creator_mypage' user.pk %}">크리에이터 페이지</a><br/>
                                {% endif %}
                                <a href="/accounts/logout">로그아웃</a><br/>
                            </div>
                        {% else %}
                            <div class="dropdown-content" id="myDropdown" dir="rtl">
                                <a href="/login/">로그인</a><br/>
                                <a href="/signup/">회원가입</a>
                            </div>
                        {% endif %}
                    </div>
                </form>
            </div>
        </nav>
    </header>
    <main role="main" style="height: 100%">
        {% block main %}

        {% endblock %}
    </main>
    <br/>
    <footer class="container footer">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2020 Pirogramming. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </footer>
</div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
</div>
    {% block jinheescript %}
    {% endblock %}
    {% block hanseokscript %}
    {% endblock %}
    {% block injiscript %}
    {% endblock %}
    {% block kiyunscript %}
    {% endblock %}
</body>
</html>